server:
  host: localhost
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: oko

env: local

redis:
  host: localhost
  port: 6379
  password: redis

